/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark.example;

import spark.Spark;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Spark.get("/user/get/:username", (req, res) -> {
            String username = req.params(":username");

            return "Get user " + username;
        });

        Spark.post("/user/post/:username", (req, res) -> {
            String username = req.params(":username");

            return "Post user " + username;
        });

        Spark.put("/user/put/:username", (req, res) -> {
            String username = req.params(":username");

            return "Put user " + username;
        });

        Spark.delete("/user/delete/:username", (req, res) -> {
            String username = req.params(":username");

            return "Delete user " + username;
        });
    }      
}
